# Generated by Django 5.2.10 on 2026-02-24 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_codigopromocional'),
        ('ofertas', '0005_vendedor_bairro_vendedor_cep_and_more'),
        ('pedidos_coletivos', '0002_alter_pedidocoletivo_status_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('gratis', 'Grátis'), ('premium', 'Premium'), ('profissional', 'Profissional')], max_length=20, unique=True, verbose_name='Plano')),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Mensal (R$)')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, help_text='Percentual cobrado sobre cada venda', max_digits=5, verbose_name='Comissão (%)')),
                ('max_ofertas_ativas', models.IntegerField(default=5, verbose_name='Máx. Ofertas Ativas')),
                ('destaque_automatico', models.BooleanField(default=False, verbose_name='Destaque Automático')),
                ('selo_premium', models.BooleanField(default=False, verbose_name='Selo Premium')),
                ('ia_criacao_ofertas', models.BooleanField(default=False, verbose_name='IA para Criar Ofertas')),
                ('analytics_avancado', models.BooleanField(default=False, verbose_name='Analytics Avançado')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de Vendedor',
                'verbose_name_plural': 'Planos de Vendedor',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra_unidade', 'Compra por Unidade'), ('compra_lote', 'Compra Coletiva (Lote)'), ('assinatura_plano', 'Assinatura de Plano Vendedor'), ('destaque_oferta', 'Destaque de Oferta'), ('estorno', 'Estorno')], max_length=25, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto')),
                ('comissao_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão VarejoUnido')),
                ('valor_liquido_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Líquido (Vendedor)')),
                ('id_transacao_mp', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transação MP')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_ref', to='compras.compra', verbose_name='Compra Unitária')),
                ('pedido_coletivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_ref', to='pedidos_coletivos.pedidocoletivo', verbose_name='Pedido Coletivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pendente', 'Pendente Pagamento')], default='ativa', max_length=15)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_renovacao', models.DateTimeField(verbose_name='Próxima Renovação')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='ofertas.vendedor', verbose_name='Vendedor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='pagamentos.planovendedor', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura de Vendedor',
                'verbose_name_plural': 'Assinaturas de Vendedores',
            },
        ),
    ]
