# Generated by Django 5.1.3 on 2026-01-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_oferta_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='endereco_retirada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço de Retirada (Opcional)'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada', 'Retirada no Local (Vendedor)'), ('entrega', 'Entrega (Delivery/Moto)'), ('ambos', 'Retirada ou Entrega')], default='retirada', max_length=15, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor do Frete (Se houver)'),
        ),
    ]
