# Generated by Django 5.1.3 on 2026-01-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_oferta_endereco_retirada_oferta_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='selo_verificado',
            field=models.BooleanField(default=False, verbose_name='Selo de Verificação (B2B/Partner)'),
        ),
    ]
