# Generated by Django 5.2.10 on 2026-02-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_vendedor_selo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual da plataforma sobre cada venda deste vendedor', max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='municipio',
            field=models.CharField(default='São Paulo', max_length=100, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='numero',
            field=models.CharField(default='S/N', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='uf',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
    ]
