# Generated by Django 5.1.3 on 2026-01-15 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_indicacao',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Indicação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to=settings.AUTH_USER_MODEL, verbose_name='Indicado Por'),
        ),
    ]
