# Generated by Django 5.1.3 on 2026-01-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_codigopromocional'),
        ('pedidos_coletivos', '0002_alter_pedidocoletivo_status_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave de Acesso (SEFAZ)')),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do PDF')),
                ('xml_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do XML')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando na API'), ('emitida', 'Emitida com Sucesso'), ('erro', 'Erro na Emissão'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status da Emissão')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Log de Erros')),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_fiscal', to='compras.compra', verbose_name='Compra')),
                ('pedido_coletivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_fiscal', to='pedidos_coletivos.pedidocoletivo', verbose_name='Pedido Coletivo')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
    ]
