# Generated by Django 5.1.3 on 2026-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código (ex: BEMVINDO10)')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_disponivel', models.IntegerField(default=100, verbose_name='Qtd Disponível')),
            ],
        ),
    ]
